# Generated by Django 2.2.6 on 2019-11-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toosimpleq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('QUEUED', 'QUEUED'), ('PROCESSING', 'PROCESSING'), ('FAILED', 'FAILED'), ('SUCCEEDED', 'SUCCEEDED'), ('INVALID', 'INVALID'), ('INTERRUPTED', 'INTERRUPTED')], default='QUEUED', max_length=32),
        ),
    ]
