# Generated by Django 2.2.6 on 2019-12-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toosimpleq", "0002_auto_20191101_1838"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="queue",
            field=models.CharField(default="default", max_length=32),
        ),
    ]
