# Generated by Django 3.0.6 on 2021-06-14 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("toosimpleq", "0005_auto_20210302_1748"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="replaced_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="toosimpleq.Task",
            ),
        ),
    ]
