# Generated by Django 3.2.5 on 2021-09-02 19:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("toosimpleq", "0007_schedule_datetime_kwarg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="last_check",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="last_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="toosimpleq.task",
            ),
        ),
    ]
