# Generated by Django 3.2.5 on 2021-09-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("toosimpleq", "0008_auto_20210902_2111"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
