# Generated by Django 3.2.12 on 2022-03-23 20:40

import django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("toosimpleq", "0009_auto_20210902_2245"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Schedule",
            new_name="ScheduleExec",
        ),
        migrations.RenameModel(
            old_name="Task",
            new_name="TaskExec",
        ),
        migrations.AlterModelOptions(
            name="scheduleexec",
            options={"verbose_name": "Schedule Execution"},
        ),
        migrations.AlterModelOptions(
            name="taskexec",
            options={"verbose_name": "Task Execution"},
        ),
        migrations.RenameField(
            model_name="taskexec",
            old_name="function",
            new_name="task_name",
        ),
        migrations.RenameField(
            model_name="scheduleexec",
            old_name="last_check",
            new_name="last_tick",
        ),
        migrations.AlterField(
            model_name="scheduleexec",
            name="last_tick",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name="scheduleexec",
            name="args",
        ),
        migrations.RemoveField(
            model_name="scheduleexec",
            name="catch_up",
        ),
        migrations.RemoveField(
            model_name="scheduleexec",
            name="cron",
        ),
        migrations.RemoveField(
            model_name="scheduleexec",
            name="datetime_kwarg",
        ),
        migrations.RemoveField(
            model_name="scheduleexec",
            name="function",
        ),
        migrations.RemoveField(
            model_name="scheduleexec",
            name="kwargs",
        ),
        migrations.AddField(
            model_name="scheduleexec",
            name="state",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INVALID", "Invalid")],
                default="ACTIVE",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="taskexec",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="taskexec",
            name="state",
            field=models.CharField(
                choices=[
                    ("SLEEPING", "Sleeping"),
                    ("QUEUED", "Queued"),
                    ("PROCESSING", "Processing"),
                    ("SUCCEEDED", "Succeeded"),
                    ("INTERRUPTED", "Interrupted"),
                    ("FAILED", "Failed"),
                    ("INVALID", "Invalid"),
                ],
                default="QUEUED",
                max_length=32,
            ),
        ),
        migrations.RemoveField(
            model_name="taskexec",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="taskexec",
            name="queue",
        ),
    ]
