# Generated by Django 3.2.5 on 2022-03-24 03:19

import django.db.models.deletion
import django.utils.timezone
import picklefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toosimpleq", "0009_auto_20210902_2245"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleExec",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=1024, unique=True)),
                (
                    "last_check",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INVALID", "Invalid")],
                        default="ACTIVE",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Execution",
            },
        ),
        migrations.CreateModel(
            name="TaskExec",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("task_name", models.CharField(max_length=1024)),
                (
                    "args",
                    picklefield.fields.PickledObjectField(
                        blank=True, default=list, editable=False
                    ),
                ),
                (
                    "kwargs",
                    picklefield.fields.PickledObjectField(
                        blank=True, default=dict, editable=False
                    ),
                ),
                ("queue", models.CharField(default="default", max_length=32)),
                ("priority", models.IntegerField(default=0)),
                (
                    "retries",
                    models.IntegerField(
                        default=0, help_text="retries left, -1 means infinite"
                    ),
                ),
                (
                    "retry_delay",
                    models.IntegerField(
                        default=0,
                        help_text="Delay before next retry in seconds. Will double after each failure.",
                    ),
                ),
                ("due", models.DateTimeField(default=django.utils.timezone.now)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("started", models.DateTimeField(blank=True, null=True)),
                ("finished", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SLEEPING", "Sleeping"),
                            ("PROCESSING", "Processing"),
                            ("FAILED", "Failed"),
                            ("SUCCEEDED", "Succeeded"),
                            ("INVALID", "Invalid"),
                            ("INTERRUPTED", "Interrupted"),
                        ],
                        default="QUEUED",
                        max_length=32,
                    ),
                ),
                (
                    "result",
                    picklefield.fields.PickledObjectField(
                        blank=True, editable=False, null=True
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("stdout", models.TextField(blank=True, default="")),
                ("stderr", models.TextField(blank=True, default="")),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="toosimpleq.taskexec",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Execution",
            },
        ),
        migrations.RemoveField(
            model_name="task",
            name="replaced_by",
        ),
        migrations.DeleteModel(
            name="Schedule",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.AddField(
            model_name="scheduleexec",
            name="last_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="toosimpleq.taskexec",
            ),
        ),
    ]
