# Generated by Django 3.2.5 on 2022-03-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toosimpleq", "0010_auto_20220323_2140"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduleexec",
            name="args",
        ),
        migrations.RemoveField(
            model_name="scheduleexec",
            name="catch_up",
        ),
        migrations.RemoveField(
            model_name="scheduleexec",
            name="cron",
        ),
        migrations.RemoveField(
            model_name="scheduleexec",
            name="datetime_kwarg",
        ),
        migrations.RemoveField(
            model_name="scheduleexec",
            name="function",
        ),
        migrations.RemoveField(
            model_name="scheduleexec",
            name="kwargs",
        ),
    ]
