# Generated by Django 4.1.5 on 2023-01-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("toosimpleq", "0011_workerstatus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scheduleexec",
            old_name="last_run",
            new_name="last_task",
        ),
        migrations.AddField(
            model_name="scheduleexec",
            name="last_due",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="scheduleexec",
            name="last_tick",
        ),
    ]
