# Generated by Django 3.2.5 on 2022-03-23 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toosimpleq", "0011_auto_20220323_2350"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskexec",
            old_name="function",
            new_name="task_name",
        ),
    ]
