# Generated by Django 3.2.5 on 2022-03-24 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toosimpleq", "0012_rename_function_taskexec_task_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scheduleexec",
            options={"verbose_name": "Schedule Execution"},
        ),
        migrations.AlterModelOptions(
            name="taskexec",
            options={"verbose_name": "Task Execution"},
        ),
    ]
