# Generated by Django 4.1.5 on 2023-01-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("toosimpleq", "0012_rename_last_run_scheduleexec_last_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerstatus",
            name="exit_log",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workerstatus",
            name="exit_code",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "Stopped"), (1, "Terminated"), (2, "Crashed")],
                null=True,
            ),
        ),
    ]
