# Generated by Django 3.2.5 on 2022-03-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toosimpleq", "0013_auto_20220324_0245"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskexec",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
