# Generated by Django 3.2.5 on 2022-03-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toosimpleq", "0014_taskexec_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleexec",
            name="state",
            field=models.CharField(
                choices=[("ACTIVE", "ACTIVE"), ("INVALID", "INVALID")],
                default="ACTIVE",
                max_length=32,
            ),
        ),
    ]
