# Generated by Django 4.1 on 2025-04-17 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("toosimpleq", "0015_taskexec_result_preview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scheduleexec",
            options={
                "permissions": [
                    ("force_run_scheduleexec", "Can force execution of schedules")
                ],
                "verbose_name": "Schedule Execution",
            },
        ),
        migrations.AlterModelOptions(
            name="taskexec",
            options={
                "permissions": [("requeue_taskexec", "Can requeue tasks")],
                "verbose_name": "Task Execution",
            },
        ),
    ]
